# -*- coding: utf-8 -*-
# Generated by Django 1.11.9
from __future__ import unicode_literals

import apps.core.models
import apps.core.validators
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dash_address', models.CharField(max_length=35, validators=[apps.core.validators.dash_address_validator])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dash_to_transfer', models.DecimalField(decimal_places=8, max_digits=16)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Initiated. Send {dash_to_transfer} DASH to {dash_address}'), (2, 'Received {dash_to_transfer} DASH. Waiting for {confirmations_number} confirmations'), (3, 'Confirmed receiving {dash_to_transfer} DASH. Initiated an outgoing transaction'), (4, 'Transaction is processed. Hash of a Ripple transaction is {outgoing_ripple_transaction_hash}'), (5, 'Time expired. Transactions to {dash_address} are no longer tracked'), (6, 'Transaction failed. Please contact our support team'), (7, 'The ripple account {ripple_address} does not trust our gateway. Please set a trust line to {gateway_ripple_address}')], default=1)),
                ('ripple_address', models.CharField(max_length=35, validators=[apps.core.validators.ripple_address_validator])),
                ('outgoing_ripple_transaction_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.core.models.TransactionStates),
        ),
        migrations.CreateModel(
            name='DepositTransactionStateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('current_state', models.CharField(max_length=500)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='core.DepositTransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GatewaySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Gateway fee (percentage)')),
                ('max_dash_miner_fee', models.DecimalField(decimal_places=8, default=Decimal('0.1'), help_text='This value is used to calculate amount that is sent in withdrawal transactions. <b>It should be the same as <code>maxtxfee</code> of your Dash node.</b>', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dash - maximal miner fee')),
                ('dash_required_confirmations', models.PositiveIntegerField(default=6, verbose_name='Dash - minimal confirmations')),
                ('transaction_expiration_minutes', models.PositiveIntegerField(default=60, verbose_name='Transaction expiration (minutes)')),
            ],
            options={
                'verbose_name': 'Gateway Settings',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='RippleWalletCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35, validators=[apps.core.validators.ripple_address_validator], verbose_name='Address')),
                ('secret', encrypted_fields.fields.EncryptedCharField(max_length=29, verbose_name='Secret key')),
            ],
            options={
                'verbose_name': 'Ripple Wallet Credentials',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dash_address', models.CharField(max_length=35, validators=[apps.core.validators.dash_address_validator])),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dash_to_transfer', models.DecimalField(decimal_places=8, max_digits=16, validators=[apps.core.validators.withdrawal_min_dash_amount_validator])),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Initiated. Send {dash_to_transfer} Dash tokens to {ripple_address} with a destination tag {destination_tag}'), (3, 'Received {dash_to_transfer} Dash tokens. Initiated an outgoing transaction'), (4, 'Transaction is processed. Hash of a Dash transaction is {outgoing_dash_transaction_hash}'), (5, 'Time expired. Transactions with the destination tag {destination_tag} are no longer tracked'), (6, 'Transaction failed. Please contact our support team')], default=1)),
                ('outgoing_dash_transaction_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.core.models.TransactionStates),
        ),
        migrations.CreateModel(
            name='WithdrawalTransactionStateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('current_state', models.CharField(max_length=500)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='core.WithdrawalTransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
