# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 11:16
from __future__ import unicode_literals

from django.db import migrations

def create_base_pages(apps, schema_editor):
    Page = apps.get_model('core', 'Page')

    Page.objects.create(slug='about', title='About')
    Page.objects.create(slug='contact-us', title='Contact Us')
    Page.objects.create(slug='terms-and-conditions', title='Terms and Conditions')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_pages),
    ]
