# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 11:16
from __future__ import unicode_literals

from django.db import migrations

LOREM_IPSUM = """
<h1>%s</h1>
<p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et 
malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, 
ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas 
semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. 
Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, 
condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean 
fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis 
tempus lacus enim ac dui. <a href="#">Donec non enim</a> in turpis pulvinar
facilisis. Ut felis.</p>

<h2>Header Level 2</h2>
<ol>
	<li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
	<li>Aliquam tincidunt mauris eu risus.</li>
</ol>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. 
Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida. 
Curabitur massa. Donec eleifend, libero at sagittis mollis, tellus est 
malesuada tellus, at luctus turpis elit sit amet quam. Vivamus pretium 
ornare est.</p>

<h3>Header Level 3</h3>
<ul>
	<li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
	<li>Aliquam tincidunt mauris eu risus.</li>
</ul>
"""


def create_base_pages(apps, schema_editor):
    Page = apps.get_model('core', 'Page')

    Page.objects.create(
        slug='about',
        title='About',
        description=LOREM_IPSUM % 'About'
    )
    Page.objects.create(
        slug='contact-us',
        title='Contact Us',
        description=LOREM_IPSUM % 'Contact Us'
    )
    Page.objects.create(
        slug='terms-and-conditions',
        title='Terms and Conditions',
        description=LOREM_IPSUM % 'Terms and Conditions'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_pages),
    ]
