# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:42
from __future__ import unicode_literals

from django.db import migrations

DEPOSIT_DESC = """
<p>So you want to deposit your DASH to Ripple network.<br />
To make it happen, follow these steps:<br />
1. Provide your Ripple address in the box, then click the Start button<br />
2. Add Trust to the &lt;ripple-address&gt; (it&#39;s important to receive funds in ripple network)<br />
3. We will provide a DASH deposit address for you.<br />
&nbsp;&nbsp;&nbsp; Please send your DASH to this generated address.<br />
&nbsp;&nbsp;&nbsp; (Don&#39;t send more than the Deposit Limit)<br />
4. After this you also will get a link to transaction, where you can check its current status.</p>

<p>Make a note, generated address will not wait forever, make a sure you send your funds in 1 hour after starting.</p>

<p>&nbsp;</p>
"""

WITHDRAW_DESC = """
<p>So you want to withdraw your DASH from Ripple network to your (or your friend) DASH address.<br />
To make it happens, follow this:<br />
1. Provide your DASH address in the box, then click the Start button<br />
2. We will provide a Ripple withdraw address for you.<br />
&nbsp;&nbsp;&nbsp; Please send your DASH to this generated address.<br />
&nbsp;&nbsp;&nbsp; (Don&#39;t send more than the Deposit Limit)<br />
3. After this you also get a link to transaction, where you can check current status</p>

<p>Make a note, generated address will not wait forever, make a sure you send your funds in 1 hour after starting.</p>

<p>&nbsp;</p>
"""


def create_howto_pages(apps, schema_editor):
    Page = apps.get_model('core', 'Page')

    Page.objects.create(
        slug='deposit',
        title='Deposit DASH to Ripple',
        description=DEPOSIT_DESC
    )
    Page.objects.create(
        slug='withdraw',
        title='Withdraw DASH from Ripple ',
        description=WITHDRAW_DESC
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20170601_1116'),
    ]

    operations = [
        migrations.RunPython(create_howto_pages),
    ]
