# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 12:20
from __future__ import unicode_literals

import apps.core.validators
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deposittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Initiated'), (2, 'In progress'), (3, 'Completed'), (4, 'Not processed'), (5, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='ripple_address',
            field=models.CharField(max_length=35, validators=[apps.core.validators.ripple_address_validator]),
        ),
    ]
