# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_deposittransactionstatechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransactionstatechange',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
