# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 19:18
from __future__ import unicode_literals

from django.db import migrations


def create_status_page(apps, schema_editor):
    Page = apps.get_model('core', 'Page')
    Page.objects.create(
        slug='status',
        title='Status of a Transaction',
    )


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0007_auto_20171120_1335'),
    )

    operations = (
        migrations.RunPython(create_status_page),
    )
