# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171201_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposittransactionstatechange',
            name='current_state',
            field=models.CharField(max_length=500),
        ),
    ]
