# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-16 12:24
from __future__ import unicode_literals

import apps.core.validators
from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171204_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='RippleWalletCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35, validators=[apps.core.validators.ripple_address_validator], verbose_name='Address')),
                ('secret', encrypted_fields.fields.EncryptedCharField(max_length=29, verbose_name='Secret key')),
            ],
            options={
                'verbose_name': 'Ripple Wallet Credentials',
            },
        ),
    ]
