# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 12:09
from __future__ import unicode_literals

import apps.core.models
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ripplewalletcredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dash_address', models.CharField(max_length=35, validators=[apps.core.validators.dash_address_validator])),
                ('dash_to_transfer', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(default=1)),
                ('incoming_ripple_transaction_hash', models.CharField(blank=True, max_length=64)),
                ('outgoing_dash_transaction_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.core.models.TransactionStates),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='dash_address',
            field=models.CharField(max_length=35, validators=[apps.core.validators.dash_address_validator]),
        ),
    ]
