# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171221_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Initiated'), (2, 'Received an incoming transaction ({dash_to_transfer} DASH). Waiting for {confirmations_number} confirmations'), (3, 'Confirmed the incoming transaction ({dash_to_transfer} DASH). Initiated an outgoing one'), (4, 'Transaction is processed. Hash of a Ripple transaction is {outgoing_ripple_transaction_hash}'), (5, 'Received 0 Dash transactions. Transactions to the address {dash_address} are no longer tracked'), (6, 'Transaction failed. Please contact our support team'), (7, 'The ripple account {ripple_address} does not trust our gateway. Please set a trust line to {gateway_ripple_address}')], default=1),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Initiated'), (3, 'Received an incoming transaction {incoming_ripple_transaction_hash} ({dash_to_transfer} DASH). Initiated an outgoing one'), (4, 'Transaction is processed. Hash of a Dash transaction is {outgoing_dash_transaction_hash}'), (5, 'Received 0 Ripple transactions. Transactions with the destination tag {destination_tag} are no longer tracked'), (6, 'Transaction failed. Please contact our support team')], default=1),
        ),
    ]
