# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171222_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalTransactionStateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('current_state', models.CharField(max_length=500)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='core.WithdrawalTransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
