# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_withdrawaltransactionstatechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='dash_to_transfer',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='dash_to_transfer',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
    ]
