# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-03 20:06
from __future__ import unicode_literals

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180102_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='dash_to_transfer',
            field=models.DecimalField(decimal_places=8, max_digits=16, validators=[apps.core.validators.withdrawal_min_dash_amount_validator]),
        ),
    ]
