# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 14:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180103_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewaySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Gateway fee (percentage)')),
                ('dash_miner_fee', models.DecimalField(decimal_places=8, default='0.001', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dash - miner fee')),
                ('dash_required_confirmations', models.PositiveIntegerField(default=6, verbose_name='Dash - minimal confirmations')),
            ],
            options={
                'verbose_name': 'Gateway Settings',
            },
        ),
    ]
