# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180104_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawaltransaction',
            name='incoming_ripple_transaction_hash',
        ),
    ]
