# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 15:45
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180104_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaysettings',
            name='dash_miner_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.001'), max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dash - miner fee'),
        ),
    ]
