# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 16:12
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180104_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatewaysettings',
            name='dash_miner_fee',
        ),
        migrations.AddField(
            model_name='gatewaysettings',
            name='max_dash_miner_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.1'), help_text='This value is used to calculate amount that is sent in withdrawal transactions. <b>It should be the same as <code>maxtxfee</code> of your Dash node.</b>', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dash - maximal miner fee'),
        ),
    ]
