# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-09 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20180105_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Initiated. Send {dash_to_transfer} DASH to {dash_address}'), (2, 'Received {dash_to_transfer} DASH. Waiting for {confirmations_number} confirmations'), (3, 'Confirmed receiving {dash_to_transfer} DASH. Initiated an outgoing transaction'), (4, 'Transaction is processed. Hash of a Ripple transaction is {outgoing_ripple_transaction_hash}'), (5, 'Time expired. Transactions to {dash_address} are no longer tracked'), (6, 'Transaction failed. Please contact our support team'), (7, 'The ripple account {ripple_address} does not trust our gateway. Please set a trust line to {gateway_ripple_address}')], default=1),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Initiated. Send {dash_to_transfer} Dash tokens to {ripple_address} with a destination tag {destination_tag}'), (3, 'Received {dash_to_transfer} Dash tokens. Initiated an outgoing transaction'), (4, 'Transaction is processed. Hash of a Dash transaction is {outgoing_dash_transaction_hash}'), (5, 'Time expired. Transactions with the destination tag {destination_tag} are no longer tracked'), (6, 'Transaction failed. Please contact our support team')], default=1),
        ),
    ]
